# -*- coding: utf-8 -*-
"""Clase_1_1_Strings_Python.ipynb

Automatically generated by Colab.

### **Universidad Nacional de Colombia sede Manizales**
#### Departamento de Ingeniería Eléctrica, Electrónica y Computación
#### *Procesamiento del Lenguaje Natural*

#### Profesor: Diego A. Pérez

## Strings en Python: Fundamentos

Los *strings* (cadenas de texto) son uno de los tipos de datos más fundamentales en Python. Se pueden definir indistintamente utilizando comillas simples (`' '`) o comillas dobles (`" "`). A continuación, exploraremos cómo crearlos, manipularlos y aplicar sus métodos integrados.
"""

# Definición básica de un string
# shift + Enter para correr una celda de Jupyter Notebook
string = "No puedo decir que no estoy en desacuerdo contigo." 

print("String original:", string)
print("Tipo de dato:", type(string)) #

"""### Selección de caracteres por índices (Slicing)


En Python, los strings son secuencias indexadas. Esto significa que podemos seleccionar caracteres individuales o subconjuntos de ellos usando corchetes `[]`:
* El primer caracter inicia en el índice `0`.
* Los índices negativos cuentan desde el final hacia atrás (ej. `-5` selecciona los últimos 5 caracteres).
* La sintaxis completa del slicing es `[inicio:fin:paso]`, donde el índice de `fin` es **exclusivo** (no se incluye en el resultado).
"""

# Selección de caracteres individuales
print("Primer caracter:", string[0])
print("Sexto caracter (índice 5):", string[5])

# Slicing: Rangos de caracteres
print("Primeros 5 caracteres:", string[:5])
print("Últimos 5 caracteres:", string[-5:])

# Slicing con inicio y fin (el de "index=5" se incluye, el de "index=15" se excluye)
print("Caracteres entre pos 5 y 15:", string[5:15])

# Slicing con paso (salteando de a 2)
print("Caracteres entre pos 5 y 15 (paso 2):", string[5:15:2])

"""### Operaciones Básicas sobre Strings

Python nos permite realizar operaciones matemáticas y lógicas directamente sobre el texto:
* **Longitud:** La función `len()` devuelve el número total de caracteres que hay en el string.
* **Pertenencia:** La sintaxis `in` corrobora si una secuencia específica está en el string.
* **Concatenación:** El signo `+` une strings. Para unir variables numéricas con texto, es necesario convertirlas primero a string (con `str()`) o usar *f-strings*.
* **Saltos de línea:** Se representan internamente con `\n`.
* **Repetición:** El signo `*` multiplica (concatena repetidamente) la secuencia.
"""

# Longitud y pertenencia
print("Largo del string:", len(string))
print("¿La palabra 'estoy' aparece en el texto?:", "estoy" in string)

# Concatenación
string2 = "Nunca pertenecería a un club que admitiera como socio a una persona como yo."
string3 = "Fuera del perro, un libro es el mejor amigo del hombre. Dentro del perro está demasiado oscuro para leer."

# Agregando 'enters' entre frases
texto_completo = string + "\n" + string2 + "\n" + string3
print("\n--- Texto Concatenado ---")
print(texto_completo)

# Mezclando strings y variables numéricas
string_a = "esta peli la ví "
n = 100
string_b = " veces"

# string_a + n + string_b -> Esto no funcionaría porque 'n' no es un string
print("\nConcatenación con conversión:", string_a + str(n) + string_b) #
print("Concatenación con f-strings:", f"{string_a}{n}{string_b}") #

# Repetición
print("\nRepetición de strings:")
print("peli" * 3)
print(("nana "*8 + "BATMAN\n") * 3)

"""### Métodos de Búsqueda y Validación

En Python, todo es un objeto. Los strings vienen con métodos integrados (`.metodo()`) extremadamente útiles para analizarlos y prepararlos en NLP:

| Método | Descripción |
|---|---|
| `.count()` | Cuenta cuántas veces aparece un substring. |
| `.find()` | Devuelve el **menor** índice donde aparece el substring (-1 si no aparece). |
| `.rfind()` | Devuelve el **mayor** índice donde aparece el substring (-1 si no aparece). |
| `.isalpha()` | Devuelve `True` si el string es únicamente alfabético. |
| `.isalnum()` | Devuelve `True` si el string es alfanumérico (letras y números). |
"""

# Búsqueda y conteo
print("Conteo de 'de':", string.count("de"))
print("Primera aparición de 'de' (find):", string.find("de"))
print("Última aparición de 'de' (rfind):", string.rfind("de"))

# Extraemos el fragmento basándonos en el índice encontrado
idx = string.find("de")
print("Extracción dinámica:", string[idx:(idx+2)])

# Validación de caracteres
print("\n¿'El10' es puramente alfabético?:", "El10".isalpha())
print("¿'El' es puramente alfabético?:", "El".isalpha())
print("¿'El10' es alfanumérico?:", "El10".isalnum())

# Ojo: Los espacios en blanco NO son considerados alfanuméricos
print("¿'El10 ' es alfanumérico (con espacio)?:", "El10 ".isalnum())

"""### Transformación, Limpieza y Estructuración

La limpieza del texto es el primer paso en cualquier pipeline de datos. Python nos facilita esta labor con métodos para limpiar ruido y estandarizar formatos:

* **Estandarización de Caja:** `.lower()` y `.upper()` cambian el texto a minúsculas o mayúsculas.
* **Limpieza de extremos:** `.strip()` remueve los caracteres "no deseados" iniciales y finales. Si no se especifica, por defecto elimina los espacios en blanco.
* **Sustitución:** `.replace('old', 'new')` devuelve un string con un substring reemplazado por otro.
* **Interacción con Listas:** `.join()` devuelve la concatenación de una lista de strings. Lo opuesto es `.split()`, que corta un string y lo convierte en lista.
"""

# Transformación de mayúsculas/minúsculas
print("Todo a minúsculas:", string.lower())
print("Todo a mayúsculas:", string.upper())

# Limpieza con strip
texto_sucio = "\n\n\n no puedo decir que.. ......   "
print("\nTexto original:", repr(texto_sucio))
print("Strip (por defecto quita espacios):", repr(texto_sucio.strip()))
print("Strip (quitando '\\n. ' específicamente):", repr(texto_sucio.strip("\n. ")))

# Reemplazo de caracteres
print("\nReemplazar 'no' por 'SI':", string.replace("no", "SI"))
print("Remover todas las 'o':", string.replace("o", "")) # Útil para eliminar símbolos

# Interacción entre Listas y Strings
lista_de_frases = ["Frases Marxistas", string, string2, string3]

# .join() une la lista insertando el separador "\n\t- " entre cada elemento
frases_marxistas = "\n\t- ".join(lista_de_frases)
print("\nResultado de .join():")
print(frases_marxistas)

# .split() revierte el proceso, devolviendo una lista de strings
print("\nResultado de .split():")
print(frases_marxistas.split("\n\t- "))

"""---
Para mayor profundidad sobre las operaciones disponibles nativamente, puedes revisar la documentación oficial: 
[Python String Methods Documentation](https://docs.python.org/3/library/stdtypes.html#string-methods).
"""